### PR TITLE
Pass resolved value to inner-next when fallback.

### PR DESCRIPTION
**Pull request by Endermanbugzjfc**

### CODE REVIEW

**Comment by Endermanbugzjfc** [comment]
My fork is so broken...

**Comment by Endermanbugzjfc** [comment]
Succeeded test: https://github.com/Endermanbugzjfc/FormInteractionFix/actions/runs/3404951846/jobs/5662566002

**Comment by Endermanbugzjfc** [comment]
Please do not forget to bump version number and create release tag, thanks.

**Comment by SOF3** [comment]
can you add unit tests to show what this has fixed?

**Comment by SOF3** [comment]
> > can you add unit tests to show what this has fixed?
> 
> In await-generator?

yes, bug fixes should also include a unit test case that used to fail but no longer fails

**Comment by Endermanbugzjfc** [comment]
> > > can you add unit tests to show what this has fixed?
> > 
> > 
> > In await-generator?
> 
> yes, bug fixes should also include a unit test case that used to fail but no longer fails

Done.

**Review by SOF3 — APPROVED** [review]

**Comment by SOF3** [comment]
> Please do not forget to bump version number and create release tag, thanks.

will do tomorrow, please remind me if I forgot

**Comment by Endermanbugzjfc** [comment]
> Please do not forget to bump version number and create release tag, thanks.

@SOF3

**Pull request merged**
